### PR TITLE
Create FAQ.md

### PR DESCRIPTION
**Pull request by rhjones777**

### CODE REVIEW

**Comment by rhjones777** [comment]
Let me know I need to do anything differently after looking at this one.

**Comment by rhjones777** [comment]
Okay, so no formatting even on the titles. Got it. I bet I didn’t refresh the FAQ page when I finished it last night, which is why I didn’t get your changes.On Jul 17, 2024, at 07:24, Jared Jones ***@***.***> wrote:﻿
The main thing is I want as little formatting as possible with the wiki so that it's not subjective. So even though the bold and italic probably looks better, I'd remove it just so that it's not subjective and easy to stay consistent. And then I updated the FAQs last night so the content is a little different now.

**Comment by rhjones777** [comment]
Should I still keep the heading formatting (ie. #) on the headings?On Jul 17, 2024, at 07:24, Jared Jones ***@***.***> wrote:﻿
The main thing is I want as little formatting as possible with the wiki so that it's not subjective. So even though the bold and italic probably looks better, I'd remove it just so that it's not subjective and easy to stay consistent. And then I updated the FAQs last night so the content is a little different now.

**Review by JaredDanielJones — CHANGES_REQUESTED** [review]
.

**Review by JaredDanielJones — APPROVED** [review]
@all-contributors please add @rhjones777 for doc
@all-contributors please add @JaredDanielJones for doc

**Comment by JaredDanielJones** [comment]
@all-contributors please add @JaredDanielJones  for doc

**Comment by JaredDanielJones** [comment]
@all-contributors please add @JaredDanielJones for doc

**Comment by JaredDanielJones** [comment]
@all-contributors please add @rhjones777  for doc

**Pull request merged**
